import { describe, expect, it } from "vitest"

import { formatDotenv, quoteDotenvValue } from "../../src/core/dotenv.js"

describe("quoteDotenvValue", () => {
  it("emits simple alphanumeric values bare", () => {
    expect(quoteDotenvValue("production")).toBe("production")
    expect(quoteDotenvValue("v1.2.3")).toBe("v1.2.3")
  })

  it("emits an empty value as nothing (KEY=)", () => {
    expect(quoteDotenvValue("")).toBe("")
  })

  it("leaves URL-shaped values bare", () => {
    expect(quoteDotenvValue("https://app.example.com")).toBe("https://app.example.com")
    expect(quoteDotenvValue("postgres://host:5432/db")).toBe("postgres://host:5432/db")
  })

  it("quotes values containing spaces", () => {
    expect(quoteDotenvValue("hello world")).toBe('"hello world"')
  })

  it("quotes and escapes double quotes, backslashes, and dollar signs", () => {
    expect(quoteDotenvValue('has"quote')).toBe('"has\\"quote"')
    expect(quoteDotenvValue("back\\slash")).toBe('"back\\\\slash"')
    expect(quoteDotenvValue("price$5")).toBe('"price\\$5"')
  })

  it("escapes newlines/tabs to a single-line form", () => {
    expect(quoteDotenvValue("line1\nline2")).toBe('"line1\\nline2"')
    expect(quoteDotenvValue("a\tb")).toBe('"a\\tb"')
  })

  it("quotes values containing # so they aren't read as comments", () => {
    expect(quoteDotenvValue("ab#cd")).toBe('"ab#cd"')
  })
})

describe("formatDotenv", () => {
  const entries = [
    { name: "ENVIRONMENT", value: "production", secret: false },
    { name: "APP_URL", value: "https://app.example.com", secret: false },
    { name: "SUPABASE_SERVICE_KEY", value: "ey J.with space", secret: true },
  ]

  it("emits KEY=value lines, quoting where needed", () => {
    const out = formatDotenv(entries)
    expect(out).toContain("ENVIRONMENT=production")
    expect(out).toContain("APP_URL=https://app.example.com")
    expect(out).toContain('SUPABASE_SERVICE_KEY="ey J.with space"')
  })

  it("includes secret values by default", () => {
    const out = formatDotenv(entries, { includeSecrets: true })
    expect(out).toContain('SUPABASE_SERVICE_KEY="ey J.with space"')
  })

  it("omits secret values (KEY= with a note) when includeSecrets is false", () => {
    const out = formatDotenv(entries, { includeSecrets: false })
    expect(out).toMatch(/^SUPABASE_SERVICE_KEY=$/m)
    expect(out).toMatch(/# .*secret.*omitted/i)
    // non-secret values still present
    expect(out).toContain("ENVIRONMENT=production")
  })

  it("prepends a header block when provided", () => {
    const out = formatDotenv(entries, { header: "# Generated by envpkt" })
    expect(out.startsWith("# Generated by envpkt\n")).toBe(true)
  })

  it("is deterministic (same input → same output)", () => {
    expect(formatDotenv(entries)).toBe(formatDotenv(entries))
  })
})
