import { execFileSync } from "node:child_process"
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs"
import { tmpdir } from "node:os"
import { dirname, join, resolve } from "node:path"
import { fileURLToPath } from "node:url"

import { afterEach, beforeEach, describe, expect, it } from "vitest"

const __testDir = dirname(fileURLToPath(import.meta.url))
const PROJECT_ROOT = resolve(__testDir, "../..")
const CLI_SRC = resolve(PROJECT_ROOT, "src/cli/index.ts")
const TSX = resolve(PROJECT_ROOT, "node_modules/.bin/tsx")

let tmpDir: string

beforeEach(() => {
  tmpDir = mkdtempSync(join(tmpdir(), "envpkt-dotenv-test-"))
})

afterEach(() => {
  rmSync(tmpDir, { recursive: true, force: true })
})

const run = (args: string[]): { stdout: string; status: number } => {
  try {
    const stdout = execFileSync(TSX, [CLI_SRC, ...args], {
      cwd: tmpDir,
      env: { ...process.env },
      encoding: "utf-8",
      timeout: 15000,
    })
    return { stdout, status: 0 }
  } catch (err) {
    const e = err as { stdout?: string; status?: number }
    return { stdout: e.stdout ?? "", status: e.status ?? 1 }
  }
}

describe("envpkt env dotenv", () => {
  it("emits env defaults in .env format (no `export` prefix)", () => {
    const toml = `version = 1\n\n[env.ENVIRONMENT]\nvalue = "production"\n\n[env.APP_URL]\nvalue = "https://app.example.com"\n`
    writeFileSync(join(tmpDir, "envpkt.toml"), toml)

    const { stdout, status } = run(["env", "dotenv"])
    expect(status).toBe(0)
    expect(stdout).toContain("ENVIRONMENT=production")
    expect(stdout).toContain("APP_URL=https://app.example.com")
    // .env format, not shell export syntax
    expect(stdout).not.toContain("export ")
  })

  it("quotes values that need it", () => {
    const toml = `version = 1\n\n[env.GREETING]\nvalue = "hello world"\n`
    writeFileSync(join(tmpDir, "envpkt.toml"), toml)

    const { stdout } = run(["env", "dotenv"])
    expect(stdout).toContain('GREETING="hello world"')
  })

  it("includes a generated header", () => {
    const toml = `version = 1\n\n[env.X]\nvalue = "1"\n`
    writeFileSync(join(tmpDir, "envpkt.toml"), toml)

    const { stdout } = run(["env", "dotenv"])
    expect(stdout).toContain("# Generated by envpkt")
  })

  it("writes to a file with -o, keeping stdout clean", () => {
    const toml = `version = 1\n\n[env.ENVIRONMENT]\nvalue = "production"\n`
    writeFileSync(join(tmpDir, "envpkt.toml"), toml)

    const outPath = join(tmpDir, ".env.out")
    const { stdout, status } = run(["env", "dotenv", "-o", outPath])
    expect(status).toBe(0)
    // success message goes to stderr; stdout stays empty so redirects are clean
    expect(stdout).toBe("")

    const fileContent = readFileSync(outPath, "utf-8")
    expect(fileContent).toContain("ENVIRONMENT=production")
    expect(fileContent.endsWith("\n")).toBe(true)
  })

  it("applies the namespace to wire names", () => {
    const toml = `version = 1\n\n[namespace]\nprefix = "CIV"\n\n[env.GREETING]\nvalue = "hello"\n`
    writeFileSync(join(tmpDir, "envpkt.toml"), toml)

    const { stdout } = run(["env", "dotenv"])
    expect(stdout).toContain("CIV__GREETING=hello")
  })
})
