import { writeFileSync } from "node:fs"
import { dirname } from "node:path"

import { stringify } from "smol-toml"

import { resolveConfig } from "../../core/catalog.js"
import { loadConfig, resolveConfigPath } from "../../core/config.js"
import { BLUE, BOLD, CYAN, DIM, formatConfigSource, formatError, GREEN, RED, RESET, YELLOW } from "../output.js"

type ResolveOptions = {
  readonly config?: string
  readonly output?: string
  readonly format?: string
  readonly dryRun?: boolean
}

export const runResolve = (options: ResolveOptions): void => {
  const configResult = resolveConfigPath(options.config)

  configResult.fold(
    (err) => {
      console.error(formatError(err))
      process.exit(2)
    },
    ({ path: configPath, source }) => {
      const sourceMsg = formatConfigSource(configPath, source)
      if (sourceMsg) console.error(sourceMsg)
      const loadResult = loadConfig(configPath)

      loadResult.fold(
        (err) => {
          console.error(formatError(err))
          process.exit(2)
        },
        (config) => {
          const configDir = dirname(configPath)
          const resolveResult = resolveConfig(config, configDir)

          resolveResult.fold(
            (err) => {
              console.error(formatError(err))
              process.exit(2)
            },
            (result) => {
              const outputFormat = options.format ?? "toml"
              const content =
                outputFormat === "json"
                  ? `${JSON.stringify(result.config, null, 2)}\n`
                  : `# Generated by envpkt resolve — do not edit\n${stringify(result.config)}\n`

              if (options.dryRun) {
                console.log(`${DIM}# Dry run — would write:${RESET}`)
                console.log(content)
              } else if (options.output) {
                writeFileSync(options.output, content, "utf-8")
                console.log(`${GREEN}✓${RESET} Resolved config written to ${BOLD}${options.output}${RESET}`)
              } else {
                process.stdout.write(content)
              }

              if (result.catalogPath) {
                const summaryTarget = options.output ? process.stdout : process.stderr
                summaryTarget.write(
                  `\n${BOLD}${CYAN}Catalog:${RESET} ${BLUE}${result.catalogPath}${RESET}\n` +
                    `${GREEN}Merged:${RESET} ${BOLD}${result.merged.length}${RESET} key(s)${
                      result.overridden.length > 0
                        ? ` ${YELLOW}(${result.overridden.length} overridden: ${BOLD}${result.overridden.join(`${RESET}${YELLOW}, ${BOLD}`)}${RESET}${YELLOW})${RESET}`
                        : ""
                    }\n`,
                )
                result.warnings.forEach((w) => {
                  summaryTarget.write(`${RED}Warning:${RESET} ${w}\n`)
                })
              }
            },
          )
        },
      )
    },
  )
}
