import { execFileSync } from "node:child_process"
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs"
import { tmpdir } from "node:os"
import { dirname, join, resolve } from "node:path"
import { fileURLToPath } from "node:url"

import { afterEach, beforeEach, describe, expect, it } from "vitest"

const __testDir = dirname(fileURLToPath(import.meta.url))
const PROJECT_ROOT = resolve(__testDir, "../..")
const CLI_SRC = resolve(PROJECT_ROOT, "src/cli/index.ts")
const TSX = resolve(PROJECT_ROOT, "node_modules/.bin/tsx")

let tmpDir: string

beforeEach(() => {
  tmpDir = mkdtempSync(join(tmpdir(), "envpkt-resolve-e2e-"))
})

afterEach(() => {
  rmSync(tmpDir, { recursive: true, force: true })
})

const run = (
  args: string[],
  opts?: { cwd?: string; env?: Record<string, string> },
): { stdout: string; stderr: string; output: string; status: number } => {
  try {
    const stdout = execFileSync(TSX, [CLI_SRC, ...args], {
      cwd: opts?.cwd ?? tmpDir,
      env: { ...process.env, ...opts?.env },
      stdio: "pipe",
      encoding: "utf-8",
    })
    return { stdout, stderr: "", output: stdout, status: 0 }
  } catch (err: unknown) {
    const e = err as { stdout?: string; stderr?: string; status?: number }
    const stdout = e.stdout ?? ""
    const stderr = e.stderr ?? ""
    return { stdout, stderr, output: stdout + stderr, status: e.status ?? 1 }
  }
}

const writeCatalog = (): void => {
  writeFileSync(
    join(tmpDir, "catalog.toml"),
    `version = 1

[meta.DATABASE_URL]
service = "postgres"
purpose = "Primary database"
capabilities = ["SELECT", "INSERT", "UPDATE", "DELETE"]
created = "2025-11-01"
expires = "2026-11-01"

[meta.REDIS_URL]
service = "redis"
purpose = "Cache"
created = "2025-11-01"
expires = "2026-11-01"
`,
  )
}

const writeAgentConfig = (content: string): string => {
  const path = join(tmpDir, "agent.toml")
  writeFileSync(path, content)
  return path
}

describe("envpkt resolve e2e", () => {
  it("resolves catalog and outputs TOML", () => {
    writeCatalog()
    const agentPath = writeAgentConfig(`
version = 1
catalog = "catalog.toml"

[agent]
name = "test-agent"
consumer = "agent"
secrets = ["DATABASE_URL", "REDIS_URL"]
`)

    const { stdout, status } = run(["resolve", "-c", agentPath])
    expect(status).toBe(0)
    expect(stdout).toContain("Generated by envpkt resolve")
    expect(stdout).toContain("postgres")
    expect(stdout).toContain("redis")
  })

  it("resolves catalog and outputs JSON with --format json", () => {
    writeCatalog()
    const agentPath = writeAgentConfig(`
version = 1
catalog = "catalog.toml"

[agent]
name = "test-agent"
secrets = ["DATABASE_URL"]
`)

    const { stdout, status } = run(["resolve", "-c", agentPath, "--format", "json"])
    expect(status).toBe(0)
    const data = JSON.parse(stdout)
    expect(data.meta.DATABASE_URL.service).toBe("postgres")
    expect(data.catalog).toBeUndefined()
  })

  it("writes to file with -o flag", () => {
    writeCatalog()
    const agentPath = writeAgentConfig(`
version = 1
catalog = "catalog.toml"

[agent]
name = "file-agent"
secrets = ["REDIS_URL"]
`)
    const outPath = join(tmpDir, "resolved.toml")

    const { stdout, status } = run(["resolve", "-c", agentPath, "-o", outPath])
    expect(status).toBe(0)
    expect(stdout).toContain("Resolved config written")

    const content = readFileSync(outPath, "utf-8")
    expect(content).toContain("redis")
    expect(content).toContain("Generated by envpkt resolve")
  })

  it("fails for missing catalog", () => {
    const agentPath = writeAgentConfig(`
version = 1
catalog = "nonexistent.toml"

[agent]
name = "bad-agent"
secrets = ["KEY"]
`)

    const { status, output } = run(["resolve", "-c", agentPath])
    expect(status).toBeGreaterThan(0)
    expect(output).toContain("Catalog not found")
  })

  it("fails for secret not in catalog", () => {
    writeCatalog()
    const agentPath = writeAgentConfig(`
version = 1
catalog = "catalog.toml"

[agent]
name = "bad-agent"
secrets = ["NONEXISTENT_KEY"]
`)

    const { status, output } = run(["resolve", "-c", agentPath])
    expect(status).toBeGreaterThan(0)
    expect(output).toContain("not found in catalog")
  })

  it("applies agent override (narrows capabilities)", () => {
    writeCatalog()
    const agentPath = writeAgentConfig(`
version = 1
catalog = "catalog.toml"

[agent]
name = "readonly-agent"
secrets = ["DATABASE_URL"]

[meta.DATABASE_URL]
capabilities = ["SELECT"]
`)

    const { stdout, status } = run(["resolve", "-c", agentPath, "--format", "json"])
    expect(status).toBe(0)
    const data = JSON.parse(stdout)
    expect(data.meta.DATABASE_URL.capabilities).toEqual(["SELECT"])
    expect(data.meta.DATABASE_URL.service).toBe("postgres")
  })

  it("works for config without catalog (passthrough)", () => {
    writeFileSync(join(tmpDir, "simple.toml"), `version = 1\n[meta.KEY]\nservice = "svc"\n`)

    const { stdout, status } = run(["resolve", "-c", join(tmpDir, "simple.toml"), "--format", "json"])
    expect(status).toBe(0)
    const data = JSON.parse(stdout)
    expect(data.meta.KEY.service).toBe("svc")
  })
})
